### ISSUE TITLE
Can someone help me?

### ISSUE THREAD

**Issue by victorroep** [mvegter197/NeedForSkins#1]
Hi there, my name is Victor, and I am trying to set up a csgojackpot-like website.
I have hosting, domain, knowledge in HTML and pretty advanced knowledge in CSS and JS.
Problem is, I know next to nothing about PHP, and nothing at all about setting up databases.
Any help is greatly appericiated!
I have Skype, TS, Steam and so on.

**Comment by enizunic93** [comment]
Add me on steam to talk http://steamcommunity.com/id/enizunic93/
